### ISSUE TITLE
NamedFrom support

### ISSUE THREAD

**Issue by Globegitter** [nathan/pax#40]
Just found pax and love the idea -, but running into an issue with https://github.com/nathan/pax/blob/master/pax/src/es6.rs#L278 when trying it out on one of our projects - is that something difficult to implement? If I would know how to do it I would be very happy to contribute, but have very little experience with rust and even less with parser/bundler implementations.

**Comment by nathan** [comment]
Oops, I forgot I never actually implemented those. I'll get right on it.

**Comment by nathan** [comment]
I just published v0.2.2, which fixes support for `export * from '<module>'` and `export { <names> } from '<module>'`. Let me know if you run into any issues. Thanks for reporting!

**Comment by Globegitter** [comment]
Amazing, thanks for the quick fix.
