### ISSUE TITLE
ModuleNotFound when running cargo test

### ISSUE THREAD

**Issue by dtolnay** [nathan/pax#44]
A local `cargo test` fails for me with the following errors. I see the same three failures in [the first CI build](https://travis-ci.org/nathan/pax/jobs/406343619).

```console
failures:

---- test::bench_cjs_simple stdout ----
thread 'test::bench_cjs_simple' panicked at 'called `Result::unwrap()` on an `Err` value: ModuleNotFound { context: "examples/simple/index.js", name: "itt" }', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- test::bench_es6_everywhere_simple stdout ----
thread 'test::bench_es6_everywhere_simple' panicked at 'called `Result::unwrap()` on an `Err` value: ModuleNotFound { context: "examples/es6-everywhere-simple/index.js", name: "itt" }', libcore/result.rs:945:5

---- test::bench_es6_simple stdout ----
thread 'test::bench_es6_simple' panicked at 'called `Result::unwrap()` on an `Err` value: ModuleNotFound { context: "examples/es6-simple/index.mjs", name: "itt" }', libcore/result.rs:945:5


failures:
    test::bench_cjs_simple
    test::bench_es6_everywhere_simple
    test::bench_es6_simple
```

**Comment by nathan** [comment]
You have to run `npm install` in each example folder. Is there a good/sane way to make Cargo do this automatically?

**Comment by dtolnay** [comment]
I would recommend three possibilities with most preferred first:

- Have each benchmark check for a node_modules directory and shells out to `npm install` if there is not one.
- Add a comment in test.rs explaining the required setup steps.
- Have each benchmark check for a node_modules directory and fail with instructions for how to run `npm install` yourself.
