### ISSUE TITLE
Question: how to build SASS files?

### ISSUE THREAD

**Issue by limonte** [nathan/pax#50]
There's nothing nor in https://pax.js.org/ neither in this repo with `sass`/`scss` keywords. 

IMO that's a must for the modern front-end development, e.g. the parcel's docs about the subject: https://parceljs.org/assets.html#scss

Is it possible to build SASS with Pax?

**Comment by nathan** [comment]
Pax is a JavaScript bundler. In the spirit of "do one thing and do it well," it is only a JavaScript bundler. You can use a different tool for your SASS/SCSS/CSS/etc.

**Comment by limonte** [comment]
Roger, thanks!

**Comment by Timmmm** [comment]
Agreed. Webpack's support for plugins is a pretty huge feature - if this is supposed to compete with Webpack it's an important consideration that it doesn't support importing CSS, Vue, etc.
