### ISSUE TITLE
support exporting async functions

### ISSUE THREAD

**Issue by wmhilton** [nathan/pax#58]
Currently if I run pax on a project that contains something like:
```js
export async function foo () {
}
```
pax fails with:
```js
pax: expected keyword 'default' or '*' or '{' or declaration
```

but if I rewrite it as:
```js
export { foo }
async function foo () {
}
```
it doesn't throw an error, which leads me to suspect pax is tripping on the word `"async"`

**Comment by nathan** [comment]
Duplicate of #14. Thanks for reporting!
