### ISSUE TITLE
Question: Does pax perform tree-shaking

### ISSUE THREAD

**Issue by xmclark** [nathan/pax#65]
Other bundlers like rollup and webpack can tree-shake ES6 imports. Does pax do this?

**Comment by nathan** [comment]
It does not. Pax is intended for development, not production, so it focuses on speed, not the size of the output bundle.

**Comment by nafg** [comment]
Shouldn't it say this in the readme? I didn't get that impression.

**Comment by nathan** [comment]
> Shouldn't it say this in the readme? I didn't get that impression.

> **Use Pax while you’re developing,** and iterate to your heart’s content. **Use your super-cool, magical, slow-as-molasses bundler for releases,** when you don’t care how long it takes to run.
