### ISSUE TITLE
Pax does not recognize native node import

### ISSUE THREAD

**Issue by sledorze** [nathan/pax#67]
this is happening with nodeJs files like `_stream_duplex`

```javascript
    var Duplex = require('_stream_duplex');
```

**Comment by nathan** [comment]
Is this a supported/documented feature of node.js?

**Comment by sledorze** [comment]
I think we should have a way to say to pax; this is a list of modules to keep as required / imported and not try to resolve them.

That way we can specify a specific list for a nodeJs version, on need.

Maybe as part of some config / with plugins / whatever as the needs may be diverse and list(s) of modules long.

We can elaborate further if the scope is accepted.

**Comment by nathan** [comment]
v0.3.1 includes the `--external` (`-x`) option, which lets you specify a comma-separated list of modules not to resolve:

```sh
$ px --external _stream_duplex input.js output.js
```
