### ISSUE TITLE
pax doesn't look at the `browser` field

### ISSUE THREAD

**Issue by chee** [nathan/pax#74]
From the [npm package.json docs](https://docs.npmjs.com/files/package.json#browser): 

> If your module is meant to be used client-side the browser field should be used instead of the main field.

When bundling with pax, a target is not found if it specifies a `browser` field instead of a `main` field

**Comment by nathan** [comment]
Thanks for the report! This is being worked on in #73

**Comment by chee** [comment]
oh! how did i not see that! thank-you !  💕

**Comment by nathan** [comment]
I'll keep this open until #73 is actually merged, so people can find it.

**Comment by nathan** [comment]
Merged! Use `px --for-browser` (`px -b` for short) to perform `browser` field substitutions.
