### ISSUE TITLE
Consider shebangs in JS files

### ISSUE THREAD

**Issue by cuchi** [nathan/pax#75]
Executable node scripts beginning with a `#!` cannot be bundled with Pax at the moment.

Here is an example:
```javascript
#!/usr/bin/env node

console.log('Hello')

```

This fails with `unexpected # at /home/.../hello.js:1,1-2`

**Comment by nathan** [comment]
Pax should definitely accept those. Thanks for the bug report!

**Comment by cuchi** [comment]
It's kinda complicated, I'll try to be brief:

- We are currently working on a tool system for our private compiler, which compiles a custom DSL to JavaScript (Node.js).
- This generated JavaScript code depends on a runtime that embeds a lot of the compiler code (i.e. to do stuff like `eval`).
- The compiler itself is written in OCaml, then compiled via Js_of_ocaml to be exported as a module dependency for the runtime.

Our current use case is to take the **all** the generated code (which may begin with an executable) and put it into a single redistributable JS file.

We tried to use [Rollup.js](https://github.com/rollup/rollup), but the build takes at least 10 minutes.
With Pax it is literally 1200 times faster, taking only a half second.

This is an amazing tool, thanks for the good work!

**Comment by nathan** [comment]
Glad I could save you some time!

The (somewhat poorly written) [TC39 proposal](https://github.com/tc39/proposal-hashbang) for shebangs only allows them as the first token in the file, including whitespace/comments; I'm inclined to follow suit. Would that cover all your use cases?

**Comment by cuchi** [comment]
Yes, it would!
