### ISSUE TITLE
Problem installing in windows

### ISSUE THREAD

**Issue by dy** [nathan/pax#81]
After installing rust, I run:

```
C:\WINDOWS\system32>cargo install pax
    Updating crates.io index
  Installing pax v0.4.0
   Compiling winapi v0.3.7
   Compiling proc-macro2 v0.4.30
   Compiling libc v0.2.58
   Compiling memchr v2.2.0
   Compiling unicode-xid v0.1.0
   Compiling winapi-build v0.1.1
   Compiling bitflags v1.1.0
   Compiling syn v0.15.39
   Compiling byteorder v1.3.2
error: linker `link.exe` not found
  |
  = note: The system cannot find the file specified. (os error 2)

note: the msvc targets depend on the msvc linker but `link.exe` was not found

note: please ensure that VS 2013, VS 2015 or VS 2017 was installed with the Visual C++ option

error: aborting due to previous error

error: Could not compile `libc`.
warning: build failed, waiting for other jobs to finish...
error: linker `link.exe` not found
  |
  = note: The system cannot find the file specified. (os error 2)

note: the msvc targets depend on the msvc linker but `link.exe` was not found

note: please ensure that VS 2013, VS 2015 or VS 2017 was installed with the Visual C++ option

error: aborting due to previous error

error: Could not compile `bitflags`.
warning: build failed, waiting for other jobs to finish...
error: linker `link.exe` not found
  |
  = note: The system cannot find the file specified. (os error 2)

note: the msvc targets depend on the msvc linker but `link.exe` was not found

note: please ensure that VS 2013, VS 2015 or VS 2017 was installed with the Visual C++ option

error: aborting due to previous error

error: Could not compile `proc-macro2`.
warning: build failed, waiting for other jobs to finish...
error: linker `link.exe` not found
  |
  = note: The system cannot find the file specified. (os error 2)

note: the msvc targets depend on the msvc linker but `link.exe` was not found

note: please ensure that VS 2013, VS 2015 or VS 2017 was installed with the Visual C++ option

error: aborting due to previous error

error: Could not compile `syn`.
warning: build failed, waiting for other jobs to finish...
error: linker `link.exe` not found
  |
  = note: The system cannot find the file specified. (os error 2)

note: the msvc targets depend on the msvc linker but `link.exe` was not found

note: please ensure that VS 2013, VS 2015 or VS 2017 was installed with the Visual C++ option

error: aborting due to previous error

error: Could not compile `memchr`.
warning: build failed, waiting for other jobs to finish...
error: linker `link.exe` not found
  |
  = note: The system cannot find the file specified. (os error 2)

note: the msvc targets depend on the msvc linker but `link.exe` was not found

note: please ensure that VS 2013, VS 2015 or VS 2017 was installed with the Visual C++ option

error: aborting due to previous error

error: Could not compile `byteorder`.
warning: build failed, waiting for other jobs to finish...
error: linker `link.exe` not found
  |
  = note: The system cannot find the file specified. (os error 2)

note: the msvc targets depend on the msvc linker but `link.exe` was not found

note: please ensure that VS 2013, VS 2015 or VS 2017 was installed with the Visual C++ option

error: aborting due to previous error

error: failed to compile `pax v0.4.0`, intermediate artifacts can be found at `C:\Users\dfcre\AppData\Local\Temp\cargo-installWC1A04`

Caused by:
  Could not compile `winapi`.

To learn more, run the command again with --verbose.
```

**Comment by nathan** [comment]
Do you have Visual Studio 2013, 2015, or 2017 installed, and did you install it with the Visual C++ option?

**Comment by dy** [comment]
Installing 18+Gb of VS building tools helped, thanks @nathan!

If pax had a wasm entry and was delivered via npm #52, that issue wouldn't pop up. Pretty unpleasant experience - installing that MS stuff.

Also, if pax had wasm, it'd also allow to use it from external tools/packages, eg dev servers, like [budo](https://ghub.io/budo). [swc](https://github.com/swc-project) does that, for example.

**Comment by nathan** [comment]
> if pax had wasm

Pax doesn't need wasm for this. There is a working [prebuilt binaries](https://github.com/nathan/pax/releases/tag/pax-v0.4.1-alpha) system; I just need to finish up a few things I've been too busy to work on so I can do a non-alpha release with prebuilt binaries. Then you can just download the binary and put it in the right place, and I'll publish an npm package that does that for you. (This is how all non-JS tools that install via npm work. They don't use wasm.)

> if pax had wasm, it'd also allow to use it from external tools/packages

Wasm also wouldn't help with that at all. As it stands, you certainly can use Pax from external tools: just invoke it via the `spawn` equivalent in whatever language you're using. I think you mean you want a node.js API for Pax. That's not a high priority for me, but it's also not particularly difficult to implement; feel free to open an issue for it.

**Comment by chpio** [comment]
> Then you can just download the binary and put it in the right place [...] (This is how all non-JS tools that install via npm work. They don't use wasm.)

Just if there's no way to build a wasm file like in `puppeteer`, you can't just build a chromium wasm file. But there are projects like `node-sass`/`libsass` that are going the [wasm route](https://github.com/sass/node-sass/issues/2011). Also it would be more appropriate for  `pax` to be a (wasm) *library* not an *executable*/*binary*.

One disadvantage of wasm that i can see right now is that threading is not-possible/hard in wasm.

<https://rustwasm.github.io/2018/10/24/multithreading-rust-and-wasm.html>
