### ISSUE TITLE
import Modules from "./modules";

### ISSUE THREAD

**Issue by JhonnyJason** [nathan/pax#85]
SyntaxError: Cannot use import statement outside a module

Probably there is something I don't get XD

Try to bundling it with 
```sh
~/.cargo/bin/px --no-map index.js output/service.js
```

index.js
```javascript
// Generated by CoffeeScript 2.4.1
var module, name;

import Modules from "./modules";

console.log("hello!\n");

global.allModules = Modules;

for (name in Modules) {
  module = Modules[name];
  module.initialize();
}
```

The regarding the service.js it appears that pax collects and remeber the files but does not actually resolve the imports?^^

**Comment by nathan** [comment]
Try running `px` with `--es-syntax-everywhere` (`-E`)..
