### ISSUE TITLE
Please add a license to this repo

### ISSUE THREAD

**Issue by mbrukman** [nathan/pax#90]
Thanks for releasing Pax!

Could you please add an explicit `LICENSE` file to the repo so that it's clear
under what terms the content is provided, and under what terms user
contributions are licensed?

Per [GitHub docs on licensing][github-docs-licensing]:

> [...] without a license, the default copyright laws apply, meaning that you
> retain all rights to your source code and no one may reproduce, distribute,
> or create derivative works from your work. If you're creating an open source
> project, we strongly encourage you to include an open source license.

Thanks!

[github-docs-licensing]: https://help.github.com/articles/licensing-a-repository/#choosing-the-right-license

**Comment by nathan** [comment]
It already has one.

https://github.com/nathan/pax/blob/master/pax/LICENSE.md
https://github.com/nathan/pax/blob/master/esparse/LICENSE.md

**Comment by mbrukman** [comment]
Ah, I see, thanks! The thing is that there's no `LICENSE` at the top-level of the repo, and nothing mentioned in the `README`, so it's wasn't clear that one has to look separately into each subdirectory to see the licenses for the repo.

Also, in the absence of a `LICENSE` file at the top-level of the repo, GitHub cannot autodetect this repo's license as per [this blog post][license-blog-post], and hence it's not displayed in the repo overview.

What do you think about replacing the two license files in subdirectories with a single license file at the top-level of the repo instead?

[license-blog-post]: https://github.blog/2016-09-21-license-now-displayed-on-repository-overview/
